# Generated by Django 3.2.2 on 2021-10-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20211022_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
